# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\danil99152\Downloads\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 493)
        self.expand = QtWidgets.QPushButton(MainWindow)
        self.expand.setGeometry(QtCore.QRect(0, 0, 21, 491))
        self.expand.setObjectName("expand")
        self.rollup = QtWidgets.QPushButton(MainWindow)
        self.rollup.setGeometry(QtCore.QRect(310, 0, 21, 491))
        self.rollup.setObjectName("rollup")
        self.GettingSymptoms = QtWidgets.QTextEdit(MainWindow)
        self.GettingSymptoms.setGeometry(QtCore.QRect(20, 0, 291, 231))
        self.GettingSymptoms.setObjectName("textEdit")
        self.Result = QtWidgets.QListWidget(MainWindow)
        self.Result.setGeometry(QtCore.QRect(20, 260, 291, 231))
        self.Result.setObjectName("listWidget")
        self.getResult = QtWidgets.QPushButton(MainWindow)
        self.getResult.setGeometry(QtCore.QRect(20, 230, 291, 31))
        self.getResult.setObjectName("getResult")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MedService"))
        MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
        self.expand.setIcon(QIcon('back_arrow.png'))
        self.rollup.setIcon(QIcon('arrow.png'))
        self.getResult.setText(_translate("MainWindow", "Получить результат"))
